//Weather
export const GET_WEATHER_PENDING = "GET_WEATHER_PENDING";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_FAIL = "GET_WEATHER_FAIL";

//Forecast
export const GET_FORECAST_PENDING = "GET_FORECAST_PENDING";
export const GET_FORECAST_SUCCESS = "GET_FORECAST_SUCCESS";
export const GET_FORECAST_FAIL = "GET_FORECAST_FAIL";